# Generated by Django 3.0.8 on 2020-08-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
