# Generated by Django 3.0.8 on 2020-08-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200812_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='finished',
            field=models.BooleanField(default=True),
        ),
    ]
