# Generated by Django 3.0.8 on 2020-08-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewerguy', models.CharField(max_length=200, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=2)),
                ('rreview', models.CharField(default='No Review', max_length=3000)),
                ('reviewedstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Story')),
            ],
        ),
    ]
