# Generated by Django 3.0.8 on 2020-09-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='desc',
            field=models.CharField(default='This Story has no description', max_length=3000),
        ),
        migrations.AddField(
            model_name='story',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=6, max_digits=2),
        ),
    ]
